import os
from typing import List
from langchain_core.tools import tool
from langchain_ollama import ChatOllama
from langgraph.prebuilt import create_react_agent
from langchain_core.messages import HumanMessage
from qdrant_db import search_repository

def get_retrieval_tool(repository_id: str):
    @tool
    def search_codebase(query: str) -> str:
        """
        Useful for searching the codebase for code snippets, architecture details, and documentation.
        Always use this tool to find factual information about the code.
        """
        # Call the Qdrant DB search we wrote in Phase 4
        docs = search_repository(query, repository_id=repository_id, k=5)
        
        if not docs:
            return "No relevant information found in the repository."
            
        formatted_results = []
        for doc in docs:
            # Extract metadata
            file_path = doc.metadata.get("file_path", "unknown_file")
            start_line = doc.metadata.get("start_line", "?")
            end_line = doc.metadata.get("end_line", "?")
            
            # Format the output for the LLM
            formatted = f"--- FILE: {file_path} (Lines {start_line}-{end_line}) ---\n{doc.page_content}\n"
            formatted_results.append(formatted)
            
        return "\n".join(formatted_results)
    
    return search_codebase

def get_agent_executor(repository_id: str):
    """
    Initializes and returns the LangGraph ReAct agent for a specific repository.
    """
    # 1. Initialize the LLM
    llm = ChatOllama(
        model=os.getenv("OLLAMA_MODEL", "qwen3:8b"),
        temperature=0,
        base_url=os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
    )
    
    # 2. Get the tools
    tools = [get_retrieval_tool(repository_id)]
    
    # 3. Define the System Prompt
    system_prompt = f"""You are an expert software developer and Codebase Intelligence Agent. 
Your job is to answer questions about the GitHub repository: {repository_id}

CRITICAL RULES:
- You are already connected to {repository_id}. Do NOT ask the user for the repository name.
- If the human asks a question about the code, ALWAYS use the `search_codebase` tool.
- When you provide code snippets or explain architecture, you MUST cite the file path and line numbers exactly as provided in the tool output.
- Do not make up information. If it's not in the tool output, say you don't know."""
    
    # 4. Create the agent using LangGraph
    agent = create_react_agent(llm, tools=tools, prompt=system_prompt)
    
    return agent

def run_agent(repository_id: str, message: str) -> str:
    """
    Entry point to run the agent.
    """
    agent = get_agent_executor(repository_id)
    
    # LangGraph uses a list of messages
    inputs = {"messages": [HumanMessage(content=message)]}
    
    # Limit to 5 steps to prevent infinite loops if the LLM struggles with tools
    config = {"recursion_limit": 5}
    response = agent.invoke(inputs, config=config)
    
    # Return the final message content generated by the agent
    return response["messages"][-1].content
